### PR TITLE
Implement check for CHANGELOG

### LINKED ISSUE #17: CHANGELOG
ChangeLogs are a great way to communicate specific changes between versions without relying on having to read a commit log.

Maybe flint could check for the presence of a CHANGELOG file? Maybe fancier and more language specific would be checking the gemspec or package.json for a recent version, and making sure there's an entry in the ChangeLog for it?

### PR DESCRIPTION
**Pull request by pengwynn**
Closes #17, adds scanning a project for a CHANGELOG:

```
❯ flint --github pengwynn/rdio-cli
[WARNING] CHANGELOG not found
[INFO] Add a changelog to show what's changed with each release. http://keepachangelog.com/
```

/cc @technicalpickles who asked for it
/cc @olivierlacan who created the perfect link for this.

### CODE REVIEW

**Comment by tamu18115** [comment]
#18

**Comment by thedahagroup** [comment]
hi guys!! i hope you people are doing good.
may i know why are you people sending me emails? any good reason?

**Comment by technicalpickles** [comment]
@thedahagroup you are currently 'watching' this repository, so you'll get email notifications for comments and new issues on it. If you don't want to be getting these, check out https://help.github.com/articles/unwatching-repositories/

**Comment by josephholsten** [comment]
@pengwynn this looks good, need anything to get this merged?

**Pull request merged**
